packages:
  - "packages/*"
  - "tooling/*"
  - "docs-starlight"
  - "e2e"

autoInstallPeers: true
strictPeerDependencies: false
sharedWorkspaceLockfile: true
preferWorkspacePackages: true

allowBuilds:
  esbuild: true
  sharp: true
